# Generated by Django 3.1.1 on 2020-09-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_movie_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
